from typing import Any

STATUS_STOPPED = "STOPPED"
STATUS_RUNNING = "RUNNING"
STATUS_ANALYZING = "ANALYZING"
STATUS_SIGNAL_FOUND = "SIGNAL_FOUND"
STATUS_WAITING_ENTRY = "WAITING_ENTRY"
STATUS_BUYING = "BUYING"
STATUS_OPERATION_OPEN = "OPERATION_OPEN"
STATUS_WAITING_RESULT = "WAITING_RESULT"
STATUS_WIN = "WIN"
STATUS_LOSS = "LOSS"
STATUS_DRAW = "DRAW"
STATUS_SHOW_RESULT = "SHOW_RESULT"
STATUS_ERROR = "ERROR"

STATUS_WAITING_NEXT_CYCLE = "WAITING_NEXT_CYCLE"
STATUS_SIGNAL_REJECTED = "SIGNAL_REJECTED"
STATUS_ENTRY_SENT = "ENTRY_SENT"
STATUS_SENDING_ORDER = "SENDING_ORDER"
STATUS_PENDING_RESULT = "PENDING_RESULT"
STATUS_RESULT_RECEIVED = "RESULT_RECEIVED"
STATUS_WAITING_GALE_ENTRY = "WAITING_GALE_ENTRY"
STATUS_SENDING_GALE_ORDER = "SENDING_GALE_ORDER"
STATUS_PENDING_GALE_RESULT = "PENDING_GALE_RESULT"
STATUS_GALE_RESULT_RECEIVED = "GALE_RESULT_RECEIVED"
STATUS_ORDER_REJECTED = "ORDER_REJECTED"
STATUS_REAL_TRADING_LOCKED = "REAL_TRADING_LOCKED"
STATUS_WAITING_NEXT_CANDLE_ENTRY = "WAITING_NEXT_CANDLE_ENTRY"
STATUS_WAITING_ENTRY_WINDOW = STATUS_WAITING_NEXT_CANDLE_ENTRY
STATUS_WAITING_ANALYSIS_WINDOW = "WAITING_ANALYSIS_WINDOW"
STATUS_SIGNAL_EXPIRED = "SIGNAL_EXPIRED"
STATUS_STOP_WIN_HIT = "STOP_WIN_HIT"
STATUS_STOP_LOSS_HIT = "STOP_LOSS_HIT"
STATUS_ACCOUNT_DISCONNECTED = "DISCONNECTED"
STATUS_SYNCING = "SYNCING"
STATUS_SYNCING_PT = "SINCRONIZANDO"
STATUS_ANALYSIS_TIMEOUT = "ANALYSIS_TIMEOUT"
STATUS_ANALYSIS_ERROR = "ANALYSIS_ERROR"
STATUS_NO_SIGNAL_FOUND = "NO_SIGNAL_FOUND"
STATUS_NO_CANDIDATES = "NO_CANDIDATES"
STATUS_NO_CANDIDATE_THIS_CANDLE = "NO_CANDIDATE_THIS_CANDLE"
STATUS_CONNECTION_BACKOFF = "CONNECTION_BACKOFF"
STATUS_WAITING_RECOVERY = "WAITING_RECOVERY"
STATUS_ACTIVE_COOLDOWN = "ACTIVE_COOLDOWN"
STATUS_PAYOUT_COOLDOWN = "PAYOUT_COOLDOWN"
STATUS_INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE"
STATUS_BULLEX_ACTIVE_MODE_NOT_REAL = "BULLEX_ACTIVE_MODE_NOT_REAL"

FINAL_RESULT_STATUSES = {STATUS_WIN, STATUS_LOSS, STATUS_DRAW}

TEMPORARY_WAIT_STATUSES = {
    STATUS_CONNECTION_BACKOFF,
    STATUS_WAITING_RECOVERY,
    STATUS_ACTIVE_COOLDOWN,
    STATUS_PAYOUT_COOLDOWN,
    STATUS_SIGNAL_EXPIRED,
}

VALID_ROBOT_STATUSES = {
    STATUS_STOPPED,
    STATUS_RUNNING,
    STATUS_ANALYZING,
    STATUS_SIGNAL_FOUND,
    STATUS_WAITING_ENTRY,
    STATUS_BUYING,
    STATUS_OPERATION_OPEN,
    STATUS_WAITING_RESULT,
    STATUS_WIN,
    STATUS_LOSS,
    STATUS_DRAW,
    STATUS_SHOW_RESULT,
    STATUS_ERROR,
    STATUS_WAITING_NEXT_CYCLE,
    STATUS_SIGNAL_REJECTED,
    STATUS_ENTRY_SENT,
    STATUS_SENDING_ORDER,
    STATUS_PENDING_RESULT,
    STATUS_RESULT_RECEIVED,
    STATUS_WAITING_GALE_ENTRY,
    STATUS_SENDING_GALE_ORDER,
    STATUS_PENDING_GALE_RESULT,
    STATUS_GALE_RESULT_RECEIVED,
    STATUS_ORDER_REJECTED,
    STATUS_REAL_TRADING_LOCKED,
    STATUS_WAITING_NEXT_CANDLE_ENTRY,
    STATUS_WAITING_ANALYSIS_WINDOW,
    STATUS_SIGNAL_EXPIRED,
    STATUS_STOP_WIN_HIT,
    STATUS_STOP_LOSS_HIT,
    STATUS_ACCOUNT_DISCONNECTED,
    STATUS_SYNCING,
    STATUS_SYNCING_PT,
    STATUS_ANALYSIS_TIMEOUT,
    STATUS_ANALYSIS_ERROR,
    STATUS_NO_SIGNAL_FOUND,
    STATUS_NO_CANDIDATES,
    STATUS_NO_CANDIDATE_THIS_CANDLE,
    STATUS_CONNECTION_BACKOFF,
    STATUS_WAITING_RECOVERY,
    STATUS_ACTIVE_COOLDOWN,
    STATUS_PAYOUT_COOLDOWN,
    STATUS_INSUFFICIENT_BALANCE,
    STATUS_BULLEX_ACTIVE_MODE_NOT_REAL,
}

_LEGACY_STATUS_ALIASES = {
    "WAITING_ENTRY_WINDOW": STATUS_WAITING_ENTRY_WINDOW,
}


def normalize_robot_status(status: Any, *, default: str = STATUS_STOPPED) -> str:
    normalized = str(status or "").strip().upper()
    if not normalized:
        return default
    normalized = _LEGACY_STATUS_ALIASES.get(normalized, normalized)
    return normalized if normalized in VALID_ROBOT_STATUSES else default


__all__ = [name for name in globals() if name.startswith("STATUS_")] + [
    "FINAL_RESULT_STATUSES",
    "TEMPORARY_WAIT_STATUSES",
    "VALID_ROBOT_STATUSES",
    "normalize_robot_status",
]
